# Generated by Django 3.1.4 on 2021-01-02 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_image', models.ImageField(default='default_user.png', help_text=' create Profile Image', null=True, upload_to='prof_images/%Y/%m/%d/', verbose_name='Profile Image')),
                ('prof_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Profile Created Date')),
                ('prof_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Profile Updated Date')),
                ('prof_mob', models.CharField(help_text=' add Mobile Number with your country code, Example(for KSA):00966123456789', max_length=14, null=True, unique=True, verbose_name='Mobile Number')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True, verbose_name='Gender')),
                ('user_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
