# Generated by Django 3.1.4 on 2020-12-28 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_title', models.CharField(help_text="create unique title for the Category 'Max Length: 255'", max_length=255, null=True, unique=True, verbose_name='Category Title')),
                ('cat_des', models.CharField(help_text=" create short descirption about this Category 'Max Length: 255'", max_length=255, null=True, verbose_name='Category Description')),
                ('cat_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Category Created Date')),
                ('cat_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Category Updated Date')),
                ('cat_image', models.ImageField(default='default.jpg', help_text=' create Category Image', null=True, upload_to='cats_images/%Y/%m/%d/', verbose_name='Category Image')),
            ],
            options={
                'ordering': ('-cat_created',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(help_text="create unique subject of your post 'Max Length: 255'", max_length=255, null=True, unique=True, verbose_name='Post subject')),
                ('post_text', models.TextField(help_text="createyour post 'Max Length: 4000'", max_length=4000, null=True, verbose_name='Post text')),
                ('post_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Post Created Date')),
                ('post_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Post Updated Date')),
                ('post_views_counter', models.PositiveIntegerField(default=0)),
                ('post_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('cat_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_to_cat', to='blog_app.category', verbose_name='Category FK')),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_to_author', to=settings.AUTH_USER_MODEL, verbose_name='Category author')),
            ],
            options={
                'ordering': ('-post_created',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(help_text="create your Comment 'Max Length: 4000'", max_length=4000, null=True, verbose_name='Comment text')),
                ('comment_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Comment Created Date')),
                ('comment_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Comment Updated Date')),
                ('comment_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments_to_author', to=settings.AUTH_USER_MODEL, verbose_name='Comment author')),
                ('post_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_to_post', to='blog_app.post', verbose_name='Post FK')),
            ],
        ),
    ]
